### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by dbochicchio** [lanrat/hass-screenshot#12]
I love your version and I'm using it because of the realtime feature.

Could you please port dark theme support? https://github.com/sibbl/hass-lovelace-kindle-screensaver/pull/97

Thanks!

**Comment by lanrat** [comment]
You can use dark mode by adding the following flag to chrome `--force-dark-mode`. I'd happy accept a PR if someone wants to make that configurable via an environment variable.

**Comment by tuxianerDE** [comment]
@dbochicchio  Could you please also ammend the README table accordingly
