### ISSUE TITLE
Additional display counter

### ISSUE THREAD

**Issue by aptonline** [lanrat/hass-screenshot#2]
I’ve noticed that the display has some kind of counter to the bottom left  that I can’t seem to find any reference to in the docs.  Is this diagnostic related and can it be disabled?
![F31F9606-F55E-464F-8686-53BE8C8AFA6D](https://user-images.githubusercontent.com/190136/168468756-642f4426-32a5-48f6-9268-b856c5fa7e20.jpeg)

**Comment by lanrat** [comment]
Yeah, that's the time the display last updated. I'll add a TODO for myself to allow it to be disabled in the settings.

**Comment by lanrat** [comment]
My last [commit to hass-kindle-screensaver](https://github.com/lanrat/hass-kindle-screensaver/commit/67dabff87f1f705a3aa51b8ed78ebe0c89ce6814) added the `DISPLAY_REFRESH_TIME` and `DISPLAY_BATTERY_LEVEL` variables to `config.sh` which can allow you to turn this off.
