### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by aptonline** [lanrat/hass-screenshot#3]
I've trying to resize the image to fit into my photo frame but when I change the width to 550 for example the image size in the web ui is showing correctly (550) but the kindle is still showing it as the previous width (600).  The image change is not reflected on the kindle.

My understanding is that the image is drawn from the top left corner of the display and the width and height are reflected accordingly.  Maybe my understanding is incorrect.   I don't seem to have the same issue with @sibbi's version as I can change the height and width and make it fit perfectly within the mounting of the picture frame so maybe this is one of the changed you implemented.

I've also tried the scaling and while this does resize the image it still doesn't change the width of the image in the kindle.

Any help grateful.

**Comment by lanrat** [comment]
I'm not quire sure what you are trying to do.

Do you want to display an image that is not the native side to the kindle?

This repository just hosts code that takes screenshots from Home assistant. All kindle related code is here: https://github.com/lanrat/hass-kindle-screensaver

**Comment by aptonline** [comment]
I have my kindle mounted in a picture frame which is slightly narrower than the width of the kindle display. By using `RENDERING_SCREEN_WIDTH` I’m trying to adjust the width of the generated PNG so that it fits within the frames aperture.

Although the height and scale options seem to be affecting the image the width doesn’t seem to make a difference.

**Comment by aptonline** [comment]
Ok so I've checked width of the png generated by `HASS-screenshot` and it is, in this example, 550px as opposed to the default 600px which is correct based on the `RENDERING_SCREEN_WIDTH` specified. So, as you say, it appears to be an issue with how `hass-kindle-screensaver` is displaying the image on the kindle side.  I'll raise an issue on that repo.

**Comment by lanrat** [comment]
Closing this in favor of tracking in: https://github.com/lanrat/hass-kindle-screensaver/issues/1
