### ISSUE TITLE
Device showing as 'unknown device'

### ISSUE THREAD

**Issue by aptonline** [lanrat/hass-screenshot#4]
My kindle is showing as 'unknown device' and not sure how to change this is the settings as I have it set to 'Kindle 4'.

{
  "Unknown Device": {
    "name": "Unknown Device",
    "ip": "x.x.x.x",
    "mac_address": "x.x.x.x",
    "serial_number": "x.x.x.x",
    "boot_time": 1584482200,
    "wifi_signal": -50,
    "count": 175,
    "battery_level": 96,
    "charging": false,
    "last_seen": "2022-05-15T09:34:31.997Z",
    "update_interval": 1211
  }
}

**Comment by lanrat** [comment]
Set your device name in config.sh on the kindle screensaver application.

example: https://github.com/lanrat/hass-kindle-screensaver/blob/main/extensions/homeassistant/config.sh#L46
