### ISSUE TITLE
Render jpg images instead of/along png ones

### ISSUE THREAD

**Issue by kalon33** [lanrat/hass-screenshot#7]
Would it be possible to render jpg images instead of (or along) png ones? And how?
   
I found some code to display images on e-ink screen from lilygo (T5 4.7), but it is compatible only with jpg files as the rendering library specific.
   
Thanks for your help.

**Comment by lanrat** [comment]
It should not be very difficult to implement this, but I don't have the time.

I would be happy to accept a PR if you or someone else wants to add this feature.
